src/Entity/Team.php
<?php

namespace App\Entity;

use App\Entity\Trait\TimestampableEntity;
use App\Repository\TeamRepository;
use App\Validator as AppAssert;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Intl\Countries;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * A Team defines a team, league, or other organization.
 */
#[ORM\Entity(repositoryClass: TeamRepository::class)]
#[UniqueEntity('slug')]
class Team implements \Stringable
{
    use TimestampableEntity;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private int $id;

    #[ORM\Column(type: 'string', length: 255)]
    #[Assert\NotBlank]
    private string $name;

    #[ORM\Column(type: 'string', length: 255)]
    #[Assert\NotBlank]
    #[Assert\Regex('/^[a-z0-9-]+$/')]
    private string $slug;

    /** @var Collection<string|int, Roster> */
    #[ORM\OneToMany(targetEntity: Roster::class, mappedBy: 'team')]
    private Collection $rosters;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    #[Assert\Url]
    private ?string $website = null;

    #[ORM\Column(type: 'string', length: 2, nullable: true)]
    #[Assert\Country]
    private ?string $country = null;

    #[ORM\Column(type: 'integer', nullable: true)]
    private ?int $startYear = null;

    #[ORM\Column(type: 'integer', nullable: true)]
    private ?int $endYear = null;

    #[ORM\Column(type: 'string', length: 16, nullable: true)]
    #[Assert\Choice(['men', 'women'])]
    private ?string $gender = null;

    #[ORM\Column(type: 'string', length: 16, nullable: true)]
    #[AppAssert\IsSport()]
    private ?string $sport = null;

    /** @var Collection<string|int, Document> */
    #[ORM\OneToMany(targetEntity: Document::class, mappedBy: 'team')]
    private Collection $documents;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private ?string $logoFileType = null;

    #[ORM\Column(type: 'string', length: 16, nullable: true)]
    #[Assert\Choice(['teams', 'orgs'])]
    private ?string $type = null;

    #[ORM\ManyToOne(targetEntity: Team::class, inversedBy: 'subTeams')]
    private ?Team $parentTeam = null;

    /** @var Collection<string|int, Team> */
    #[ORM\OneToMany(targetEntity: Team::class, mappedBy: 'parentTeam')]
    private Collection $subTeams;

    /** @var Collection<string|int, TeamLeague> */
    #[ORM\OneToMany(targetEntity: TeamLeague::class, mappedBy: 'team')]
    private Collection $teamLeagues;

    /** @var Collection<string|int, TeamLeague> */
    #[ORM\OneToMany(targetEntity: TeamLeague::class, mappedBy: 'league')]
    private Collection $memberTeamLeagues;

    /** @var Collection<string|int, TeamName> */
    #[ORM\OneToMany(targetEntity: TeamName::class, mappedBy: 'team')]
    private Collection $names;

    public function __construct()
    {
        $this->rosters = new ArrayCollection();
        $this->documents = new ArrayCollection();
        $this->subTeams = new ArrayCollection();
        $this->teamLeagues = new ArrayCollection();
        $this->memberTeamLeagues = new ArrayCollection();
    }

    #[\Override]
    public function __toString(): string
    {
        return $this->name;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * @return Collection<string|int, Roster>
     */
    public function getRosters(): Collection
    {
        return $this->rosters;
    }

    public function addRoster(Roster $roster): self
    {
        if (!$this->rosters->contains($roster)) {
            $this->rosters[] = $roster;
            $roster->setTeam($this);
        }

        return $this;
    }

    public function removeRoster(Roster $roster): self
    {
        if ($this->rosters->removeElement($roster)) {
            // set the owning side to null (unless already changed)
            if ($roster->getTeam() === $this) {
                $roster->setTeam(null);
            }
        }

        return $this;
    }

    public function getWebsite(): ?string
    {
        return $this->website;
    }

    public function getWebsitePretty(): ?string
    {
        if ($this->website == null) {
            return null;
        }
        $pretty = preg_replace('/^https?:\\/\\/(.*)$/', '$1', (string) $this->website);
        $pretty = preg_replace("/^www\.(.*)$/", '$1', (string) $pretty);
        $pretty = preg_replace('/^(.*)\\/$/', '$1', (string) $pretty);

        return $pretty;
    }

    public function setWebsite(?string $website): self
    {
        $this->website = $website;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(?string $country): self
    {
        $this->country = $country;

        return $this;
    }

    public function getCountryName(): ?string
    {
        return Countries::getName($this->country);
    }

    public function getStartYear(): ?int
    {
        return $this->startYear;
    }

    public function setStartYear(?int $startYear): self
    {
        $this->startYear = $startYear;

        return $this;
    }

    public function getEndYear(): ?int
    {
        return $this->endYear;
    }

    public function setEndYear(?int $endYear): self
    {
        $this->endYear = $endYear;

        return $this;
    }

    public function getGender(): ?string
    {
        return $this->gender;
    }

    public function setGender(?string $gender): self
    {
        $this->gender = $gender;

        return $this;
    }

    public function getSport(): ?string
    {
        return $this->sport;
    }

    public function setSport(?string $sport): self
    {
        $this->sport = $sport;

        return $this;
    }

    /**
     * @return Collection<string|int, Document>
     */
    public function getDocuments(): Collection
    {
        return $this->documents;
    }

    public function addDocument(Document $document): self
    {
        if (!$this->documents->contains($document)) {
            $this->documents[] = $document;
            $document->setTeam($this);
        }

        return $this;
    }

    public function removeDocument(Document $document): self
    {
        if ($this->documents->removeElement($document)) {
            // set the owning side to null (unless already changed)
            if ($document->getTeam() === $this) {
                $document->setTeam(null);
            }
        }

        return $this;
    }

    public function getLogoFileType(): ?string
    {
        return $this->logoFileType;
    }

    public function setLogoFileType(?string $logoFileType): self
    {
        $this->logoFileType = $logoFileType;

        return $this;
    }

    public function getLogoUrl(): ?string
    {
        if ($this->logoFileType != null) {
            $url = $_ENV['S3_ENDPOINT'].'/';
            $url .= $_ENV['S3_LOGOS_BUCKET'].'/'.$_ENV['S3_PREFIX'];
            $url .= $this->slug.'.'.$this->logoFileType;

            return $url;
        } else {
            return '/images/placeholder-logo.svg';
        }
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(?string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getParentTeam(): ?self
    {
        return $this->parentTeam;
    }

    public function setParentTeam(?self $parentTeam): self
    {
        $this->parentTeam = $parentTeam;

        return $this;
    }

    /**
     * @return Collection<string|int, Team>
     */
    public function getSubTeams(): Collection
    {
        return $this->subTeams;
    }

    public function addSubTeam(Team $subTeam): self
    {
        if (!$this->subTeams->contains($subTeam)) {
            $this->subTeams[] = $subTeam;
            $subTeam->setParentTeam($this);
        }

        return $this;
    }

    public function removeSubTeam(Team $subTeam): self
    {
        if ($this->subTeams->removeElement($subTeam)) {
            // set the owning side to null (unless already changed)
            if ($subTeam->getParentTeam() === $this) {
                $subTeam->setParentTeam(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<string|int, TeamLeague>
     */
    public function getTeamLeagues(): Collection
    {
        return $this->teamLeagues;
    }

    public function addTeamLeague(TeamLeague $teamLeague): self
    {
        if (!$this->teamLeagues->contains($teamLeague)) {
            $this->teamLeagues[] = $teamLeague;
            $teamLeague->setTeam($this);
        }

        return $this;
    }

    public function removeTeamLeague(TeamLeague $teamLeague): self
    {
        if ($this->teamLeagues->removeElement($teamLeague)) {
            // set the owning side to null (unless already changed)
            if ($teamLeague->getTeam() === $this) {
                $teamLeague->setTeam(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<string|int, TeamLeague>
     */
    public function getMemberTeamLeagues(): Collection
    {
        return $this->memberTeamLeagues;
    }

    public function addMemberTeamLeague(TeamLeague $memberTeamLeague): self
    {
        if (!$this->memberTeamLeagues->contains($memberTeamLeague)) {
            $this->memberTeamLeagues[] = $memberTeamLeague;
            $memberTeamLeague->setLeague($this);
        }

        return $this;
    }

src/Form/TeamType.php
<?php

namespace App\Form;

use App\Entity\Team;
use App\Service\SportInfoProvider;
use Doctrine\ORM\EntityRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\CountryType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\UrlType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\File;

class TeamType extends AbstractType
{
    public function __construct(private readonly SportInfoProvider $sportInfo) {}

    #[\Override]
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name', TextType::class)
            ->add('type', ChoiceType::class, [
                'choices' => [
                    'Team' => 'teams',
                    'Organization' => 'orgs',
                ],
            ])
            ->add('slug', TextType::class)
            ->add('logo', FileType::class, [
                'label' => 'Logo',

                // unmapped means that this field is not associated to any entity property
                'mapped' => false,

                // make it optional so you don't have to re-upload the PDF file
                // every time you edit the Product details
                'required' => false,

                // unmapped fields can't define their validation using annotations
                // in the associated entity, so you can use the PHP constraint classes
                'constraints' => [
                    new File([
                        'maxSize' => '10m',
                        'mimeTypes' => [
                            'image/svg',
                            'image/svg+xml',
                            'image/png',
                        ],
                        'mimeTypesMessage' => 'Please upload a valid SVG or PNG file',
                    ]),
                ],
            ])
            ->add('website', UrlType::class, [
                'required' => false,
            ])
            ->add('country', CountryType::class, [
                'required' => false,
            ])
            ->add('startYear', IntegerType::class, [
                'required' => false,
            ])
            ->add('endYear', IntegerType::class, [
                'required' => false,
            ])
            ->add('gender', ChoiceType::class, [
                'required' => false,
                'choices' => [
                    'Men\'s' => 'men',
                    'Women\'s' => 'women',
                ],
            ])
            ->add('sport', ChoiceType::class, [
                'required' => false,
                'choices' => array_flip($this->sportInfo->getCapitalizedNames()),
            ])
            ->add('parentTeam', EntityType::class, [
                'class' => Team::class,
                'query_builder' => function (EntityRepository $er) {
                    return $er->createQueryBuilder('t')
                        ->orderBy('t.name', 'ASC');
                },
                'choice_label' => 'name',
                'required' => false,
            ])
            ->add('save', SubmitType::class)
        ;
    }

    #[\Override]
    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Team::class,
        ]);
    }
}

templates/team/headshotNew.html.twig
{% extends "base.html.twig" %}

{% block title %}Add headshot to {{ roster.year }} {{ team.name }} roster{% endblock %}

{% block body %}
  <h1>
    Add headshot to
    <a href="/teams/{{ team.slug }}/{{ roster.year }}">{{ roster.year }}</a>
    <a href="/teams/{{ team.slug }}">{{ team.name }}</a>
    roster
  </h1>
  {{ form(form) }}
{% endblock %}

templates/team/list.html.twig
{% extends "base.html.twig" %}

{% block title %}Teams{% endblock %}

{% block body %}
  <h1>Teams</h1>
  {% if is_granted('ROLE_ADMIN') %}
    <a href="/teams/new" class="btn btn-success mb-3">Create new team</a>
  {% endif %}
  <ul class="row">
    {% for team in teams %}
      <div class="col-xl-2 col-md-3 col-6 text-center mb-5">
        <a href="/teams/{{ team.slug }}">
          <img src="https://sportsarchive-team-logos.s3.amazonaws.com/{{ team.slug }}.svg" style="height:100px; margin-left:auto; margin-right:auto;" class="mb-1 d-block" alt="{{ team.name }} logo" />
          {{ team.name }}
        </a>
      </div>
    {% endfor %}
  </ul>
{% endblock %}

templates/team/new.html.twig
{% extends "base.html.twig" %}

{% block title %}Create a new team{% endblock %}

{% block body %}
  <h1>Create a new team</h1>
  {{ form(form) }}
{% endblock %}

templates/team/seasonList.html.twig
{% extends "base.html.twig" %}

{% block title %}{{ 'seasonList.title'|trans }}{% endblock %}

{% block body %}
  <h1>{{ 'seasonList.title'|trans }}</h1>
  <ul>
    {% for year in years %}
      <li>
        <a href="/seasons/{{ year.year }}">
          {{- year.year -}}
        </a>
      </li>
    {% endfor %}
  </ul>
{% endblock %}

templates/team/seasonShow.html.twig
{% extends "base.html.twig" %}

{% block title %}{{ 'seasonShow.title'|trans({'%season%': year}) }}{% endblock %}

{% block body %}
  <h1>{{ 'seasonShow.title'|trans({'%season%': year}) }}</h1>
  <ul>
    {% for roster in rosters %}
      <li>
        <a href="/rosters/{{ roster.id }}">
          {{- roster.teamName -}}
        </a>
      </li>
    {% endfor %}
  </ul>
{% endblock %}

templates/team/teamEdit.html.twig
{% extends "base.html.twig" %}

{% block title %}Edit team{% endblock %}

{% block body %}
  <h1>Edit team</h1>
  <div {{ stimulus_controller('team-edit') }}>
    {{ form(form) }}
  </div>
{% endblock %}

templates/team/teamLeagueDelete.html.twig
{% extends "base.html.twig" %}

{% block title %}Remove team from league{% endblock %}

{% block body %}
  <h1>Remove team from league</h1>
  <p>
    <strong>Team:</strong>
    <a href="/{{ teamLeague.team.type }}/{{ teamLeague.team.slug }}">
      {{- teamLeague.team.name -}}
    </a>
    {% if teamLeague.team.startYear or teamLeague.team.endYear %}
      ({{ teamLeague.team.startYear }}–{{ teamLeague.team.endYear }})
    {% endif %}
  </p>
  <p>
    <strong>League:</strong> 
    <a href="/{{ teamLeague.league.type }}/{{ teamLeague.league.slug }}">
      {{- teamLeague.league.name -}}
    </a>
    {% if teamLeague.league.startYear or teamLeague.league.endYear %}
      ({{ teamLeague.league.startYear }}–{{ teamLeague.league.endYear }})
    {% endif %}
  </p>
  <p>
    <strong>Seasons:</strong>
    {% if teamLeague.firstSeason or teamLeague.lastSeason %}
      {{ teamLeague.firstSeason }} – {{ teamLeague.lastSeason }}
    {% else %}
      <em>not set</em>
    {% endif %}
  </p>
  <p>Are you sure you want to remove this team from this league?</p>
  {{ form(form, {'attr': {'data-controller': 'delete'}}) }}
{% endblock %}

templates/team/teamLeagueNew.html.twig
{% extends "base.html.twig" %}

{% block title %}{{ team.name }} – add league{% endblock %}

{% block body %}
  <h1>
    <a href="/teams/{{ team.slug }}">{{ team.name }}</a>
    – add league
  </h1>
  {{ form(form) }}
{% endblock %}

templates/team/teamList_teams.html.twig
{% for team in teams %}
  <div class="col-xl-2 col-md-3 col-6 text-center mb-5 team">
    <a href="/teams/{{ team.slug }}">
      <img src="{{ team.logoUrl }}" class="mb-1 mx-auto team-list-logo" alt="{{ 'teamList.logo_alt'|trans({'%team%': team.name}) }}" />
      {{ team.name -}}
    </a>
    {% if is_granted('ROLE_ADMIN') %}
      <a href="/teams/{{ team.slug }}/edit" class="link-primary icon-link" title="{{ 'general.edit'|trans }}">
        <i class="i-pen"></i>
      </a>
    {% endif %}
  </div>
{% endfor %}

templates/team/teamNameDelete.html.twig
{% extends "base.html.twig" %}

{% block title %}{{ teamName.team.name }} – Delete team name{% endblock %}

{% block body %}
  <h1>{{ teamName.team.name }} – Delete team name</h1>
  <p>
    {{ teamName.name }}
    {% if teamName.language != app.request.locale and teamName.language != null %}
      ({{ teamName.language|language_name|default("general.noLanguage"|trans) }})
    {% endif %}
    {% if teamName.startYear or teamName.endYear %}
      {{ 'teamShow.teamNameYears'|trans({'%start%': teamName.startYear, '%end%': teamName.endYear}) }}
    {% endif %}
  </p>
  <p>Are you sure you want to delete this team name?</p>
  {{ form(form, {'attr': {'data-controller': 'delete'}}) }}
{% endblock %}

templates/team/teamNameNew.html.twig
{% extends "base.html.twig" %}

{% block title %}{{ team.name }} – add name{% endblock %}

{% block body %}
  <h1>
    <a href="/teams/{{ team.slug }}">{{ team.name }}</a>
    – add name
  </h1>
  {{ form(form) }}
{% endblock %}

templates/team/teamShowMembers.html.twig
{% extends "base.html.twig" %}
{% from 'team/teamShow_heading.html.twig' import makeTeamNav %}

{% block title %}{{ 'teamShow.membersTitle'|trans({'%team%': team.name}) }}{% endblock %}

{% block body %}
  {% include 'team/teamShow_heading.html.twig' %}

  {{ makeTeamNav(team, 'members') }}

  <div id="leagueTeams" class="row">
    {% if leagueTeams %}
      {% if countCurrentLTs > 0 %}
        <h2>{{ 'teamShow.teamsCurrent'|trans }}</h2>
        {% for tl in leagueTeams %}
          {% if tl.isCurrent %}
            {{ _self.makeTL(tl) }}
          {% endif %}
        {% endfor %}
      {% endif %}

      {% if countFormerLTs > 0 %}
        <h2>{{ 'teamShow.teamsFormer'|trans }}</h2>
        {% for tl in leagueTeams %}
          {% if not tl.isCurrent %}
            {{ _self.makeTL(tl) }}
          {% endif %}
        {% endfor %}
      {% endif %}

    {% else %}
      <p class="lead">{{ ('teamList.noResults_teams')|trans }}</p>
    {% endif %}
  </div>
{% endblock %}

{% macro makeTL(tl) %}
  <div class="col-xl-2 col-md-3 col-6 text-center mb-5 leagueTeam">
    <a href="/teams/{{ tl.team.slug }}">
      <img src="{{ tl.team.logoUrl }}" class="mb-1 mx-auto leagueTeam-logo" alt="{{ 'teamList.logo_alt'|trans({'%team%': tl.team.name}) }}" />
      {{ tl.team.name -}}
    </a>
    <div class="team-list-caption">
      {%- if tl.hasSeasons -%}
        (
        {%- for seasonRange in tl.seasons -%}
          {%- if seasonRange[0] == seasonRange[1] -%}
            {{- seasonRange[0] -}}
          {%- else -%}
            {{- seasonRange[0] }} – {{ seasonRange[1] -}}
          {%- endif -%}
          {%- if not loop.last %}, {% endif -%}
        {%- endfor -%}
        )
      {%- endif -%}
    </div>
  </div>
{% endmacro %}

templates/team/teamShow_heading.html.twig
<div class="team-logo-block float-md-end text-md-center">
  <img src="{{ team.logoUrl }}" alt="{{ team.name }} logo" class="team-logo-big mb-2 d-block" />
  {% if team.country %}
    <img src="/images/flags/{{ team.country }}.svg" class="team-flag" alt="{{ team.countryName }} flag" title="{{ team.countryName }}">
  {% endif %}
  {% if team.sport %}
    <i class="i-{{ sportInfo.icons[team.sport] }}" title="{{ sportInfo.capitalizedNames[team.sport] }}"></i>
  {% endif %}
  {% if team.gender %}
    {% set genderIcons = {
      'men': 'mars',
      'women': 'venus',
    }
    %}
    <i class="i-{{ genderIcons[team.gender] }}" title="{{ ('gender.'~team.gender)|trans }}"></i>
  {% endif %}
</div>
<h1>{{ team.name }}</h1>
{% if is_granted('ROLE_ADMIN') %}
  <a href="/teams/{{ team.slug }}/edit" class="btn btn-sm btn-primary mb-3">
    <i class="i-pen"></i>
    {{ ('teamShow.edit_'~team.type)|trans }}
  </a>
  <a href="/teams/{{ team.slug }}/add-name" class="btn btn-sm btn-secondary mb-3">
    <i class="i-plus"></i>
    {{ ('teamShow.addName')|trans }}
  </a>
  <a href="/teams/{{ team.slug }}/add-league" class="btn btn-sm btn-secondary mb-3">
    <i class="i-plus"></i>
    {{ ('teamShow.addLeague')|trans }}
  </a>
{% endif %}
<div class="mb-2">
  <div>
    {{ team|describe_team }}
  </div>
  {% if team.startYear or team.endYear %}
    {% if team.startYear == team.endYear %}
      <div>{{ 'teamShow.yearActive'|trans({'%year%': team.startYear}) }}</div>
    {% else %}
      <div>{{ 'teamShow.yearsActive'|trans({'%start%': team.startYear, '%end%': team.endYear}) }}</div>
    {% endif %}
  {% endif %}
  {% if team.parentTeam %}
    <div>
      {{ ('teamShow.parent_'~team.parentTeam.type)|trans }}
      <a href="/{{ team.parentTeam.type }}/{{ team.parentTeam.slug }}">
        {{ team.parentTeam.name }}
      </a>
    </div>
  {% endif %}
  {% if childTeams %}
    <div>
      {{ ('teamShow.child_'~team.type)|trans }}
      {% for child in childTeams %}
        <a href="/{{ child.type }}/{{ child.slug }}">
          {{- child.name -}}
        </a>{% if not loop.last %}, {% endif %}
      {% endfor %}
    </div>
  {% endif %}
  {% if team.website %}
    <div>
      {{ 'teamShow.website'|trans }}
      <a href="{{ team.website }}" target="_blank">
        {{ team.websitePretty }}
      </a>
    </div>
  {% endif %}
  {% if is_granted('ROLE_ADMIN') and teamNames %}
    <div>{{ 'teamShow.teamNames'|trans }}</div>
    <ul class="mb-0">
      {% for tn in teamNames %}
        <li>
          {{ tn.name }}
          {% if tn.language != app.request.locale and tn.language != null %}
            ({{ tn.language|language_name|default("general.noLanguage"|trans) }})
          {% endif %}
          {% if tn.firstSeason or tn.lastSeason %}
            {{ 'teamShow.teamNameYears'|trans({'%start%': tn.firstSeason, '%end%': tn.lastSeason}) }}
          {% endif %}
          {% if is_granted('ROLE_ADMIN') %}
            <a href="/team-names/{{ tn.id }}/edit" class="link-primary icon-link" title="{{ 'general.edit'|trans }}">
              <i class="i-pen"></i>
            </a>
            <a href="/team-names/{{ tn.id }}/delete" class="link-danger icon-link" title="{{ 'general.delete'|trans }}">
              <i class="i-trash"></i>
            </a>
          {% endif %}
        </li>
      {% endfor %}
    </ul>
  {% endif %}
  {% if leagues %}
    <div>{{ 'teamShow.teamLeagues'|trans }}</div>
    <ul>
      {% for tl in leagues %}
        <li>
          <a href="/{{ tl.league.type }}/{{ tl.league.slug }}">
            {{- tl.league.name -}}
          </a>
          {% if tl.firstSeason or tl.lastSeason %}
            {% if tl.firstSeason == tl.lastSeason %}
              {{ 'teamShow.teamLeaguesYear'|trans({'%year%': tl.firstSeason}) }}
            {% else %}
              {{ 'teamShow.teamLeaguesYears'|trans({'%start%': tl.firstSeason, '%end%': tl.lastSeason}) }}
            {% endif %}
          {% endif %}
          {% if is_granted('ROLE_ADMIN') %}
            <a href="/team-leagues/{{ tl.id }}/edit" class="link-primary icon-link" title="{{ 'general.edit'|trans }}">
              <i class="i-pen"></i>
            </a>
            <a href="/team-leagues/{{ tl.id }}/delete" class="link-danger icon-link" title="{{ 'general.delete'|trans }}">
              <i class="i-trash"></i>
            </a>
          {% endif %}
        </li>
      {% endfor %}
    </ul>
  {% endif %}
</div>

{% macro makeTeamNav(team, activeTab) %}
  <ul class="nav nav-tabs team-nav">
    {{ _self.makeTeamNavLink(team, 'team_show', 'home', activeTab=='home') }}
    {{ _self.makeTeamNavLink(team, 'team_show_members', 'members', activeTab=='members') }}
  </ul>
{% endmacro %}

{% macro makeTeamNavLink(team, route, label, isActive) %}
  <li class="nav-item">
    <a class="nav-link {% if isActive %}active" aria-current="page{% endif %}"
        href="{{ path(route, { type: team.type, slug: team.slug }) }}">
      {{- ('teamShow.nav_'~label)|trans -}}
    </a>
  </li>
{% endmacro %}