src/Entity/Document.php
<?php

namespace App\Entity;

use App\Entity\Trait\TimestampableEntity;
use App\Repository\DocumentRepository;
use App\Validator as AppAssert;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: DocumentRepository::class)]
class Document implements \Stringable
{
    use TimestampableEntity;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private int $id;

    #[ORM\Column(type: 'string', length: 255)]
    private string $fileId;

    #[ORM\Column(type: 'string', length: 255)]
    private string $filename;

    #[ORM\Column(type: 'string', length: 255)]
    private string $title;

    #[ORM\ManyToOne(targetEntity: Team::class, inversedBy: 'documents')]
    private Team $team;

    #[ORM\Column(type: 'string', length: 255, options: ['default' => 'unsorted'])]
    #[AppAssert\IsDocumentCategory()]
    private string $category = 'unsorted';

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    #[Assert\Language]
    private ?string $language = null;

    #[ORM\Column(type: 'string', length: 10000, nullable: true)]
    private ?string $notes = null;

    #[ORM\Column(type: 'boolean', options: ['default' => '0'])]
    private bool $isBookReader = false;

    #[\Override]
    public function __toString(): string
    {
        return $this->category.': '.$this->title.' ['.$this->language.']';
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFileId(): ?string
    {
        return $this->fileId;
    }

    public function setFileId(string $fileId): self
    {
        $this->fileId = $fileId;

        return $this;
    }

    public function getFilename(): ?string
    {
        return $this->filename;
    }

    public function setFilename(string $filename): self
    {
        $this->filename = $filename;

        return $this;
    }

    public function getFileUrl(): ?string
    {
        $url = $_ENV['S3_ENDPOINT'].'/';
        $url .= $_ENV['S3_DOCUMENTS_BUCKET'].'/'.$_ENV['S3_PREFIX'];
        $url .= $this->getFilePath();

        return $url;
    }

    public function getFilePath(): ?string
    {
        return $this->fileId.'/'.$this->filename;
    }

    public function getFileExtension(): ?string
    {
        return pathinfo((string) $this->filename, PATHINFO_EXTENSION);
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getTeam(): ?Team
    {
        return $this->team;
    }

    public function setTeam(?Team $team): self
    {
        $this->team = $team;

        return $this;
    }

    public function getCategory(): ?string
    {
        return $this->category;
    }

    public function setCategory(string $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getLanguage(): ?string
    {
        return $this->language;
    }

    public function setLanguage(?string $language): self
    {
        $this->language = $language;

        return $this;
    }

    public function getNotes(): ?string
    {
        return $this->notes;
    }

    public function setNotes(?string $notes): self
    {
        $this->notes = $notes;

        return $this;
    }

    public function getIsBookReader(): ?bool
    {
        return $this->isBookReader;
    }

    public function setIsBookReader(?bool $isBookReader): self
    {
        $this->isBookReader = $isBookReader;

        return $this;
    }
}

src/Form/DocumentType.php
<?php

namespace App\Form;

use App\Entity\Document;
use App\Service\DocumentInfoProvider;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\LanguageType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\File;

class DocumentType extends AbstractType
{
    public function __construct(private readonly DocumentInfoProvider $documentInfo) {}

    #[\Override]
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('file', FileType::class, [
                'label' => 'File',

                // unmapped means that this field is not associated to any entity property
                'mapped' => false,

                // only required on new documents
                'required' => $options['is_new'],

                // unmapped fields can't define their validation using annotations
                // in the associated entity, so you can use the PHP constraint classes
                'constraints' => [
                    new File([
                        'maxSize' => '1000m',
                    ]),
                ],
            ])
            ->add('title', TextType::class)
            ->add('category', ChoiceType::class, [
                'choices' => array_flip($this->documentInfo->getCategoryCapitalizedLabels()),
            ])
            ->add('language', LanguageType::class, [
                'required' => false,
                'preferred_choices' => ['en', 'fr', 'es'],
            ])
            ->add('notes', TextareaType::class, [
                'required' => false,
            ])
            ->add('save', SubmitType::class, [
                'label' => 'general.save',
            ])
        ;
        if ($options['is_new']) {
            $builder->add('saveAndAddAnother', SubmitType::class, [
                'label' => 'document.saveAndAddAnother',
            ]);
        }
    }

    #[\Override]
    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Document::class,
            'is_new' => false,
        ]);

        $resolver->setAllowedTypes('is_new', 'bool');
    }
}

src/Controller/DocumentController.php
<?php

namespace App\Controller;

use App\Entity\Document;
use App\Entity\Team;
use App\Form\DeleteType;
use App\Form\DocumentType;
use App\Repository\DocumentRepository;
use App\Repository\TeamRepository;
use App\Service\DocumentPersister;
use Doctrine\Persistence\ManagerRegistry;
use League\Flysystem\Filesystem;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\SubmitButton;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\StreamedResponse;
use Symfony\Component\HttpKernel\Exception\BadRequestHttpException;
use Symfony\Component\HttpKernel\Exception\NotAcceptableHttpException;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;
use Symfony\Component\Serializer\Encoder\JsonEncoder;
use Symfony\Component\Serializer\Normalizer\AbstractNormalizer;
use Symfony\Component\Serializer\Normalizer\ObjectNormalizer;
use Symfony\Component\Serializer\Serializer;

class DocumentController extends AbstractController
{
    public function __construct(private readonly ManagerRegistry $doctrine) {}

    #[Route(path: '/documents', name: 'document_list')]
    public function listDocuments(Request $request): Response
    {
        return $this->render('document/documentList.html.twig', []);
    }

    #[Route(path: '/documents.json', name: 'document_list_json', format: 'json')]
    public function listDocumentsJson(Request $request): Response
    {
        $pageNum = $request->query->getInt('page', 1);
        $pageSize = $request->query->getInt('size', 20);
        if ($pageNum <= 0 || $pageSize <= 0) {
            throw new BadRequestHttpException('Negative pagination not allowed');
        }
        if ($pageSize > 100) {
            throw new BadRequestHttpException('Page size too big');
        }

        /** @var DocumentRepository */
        $docRepo = $this->doctrine->getRepository(Document::class);
        $qb = $docRepo->createQueryBuilder('d')
            ->join('d.team', 't', 'WITH', 'd.team = t.id');

        /** @var array<array{'field': string, 'value': string}> */
        $filters = $request->query->all('filters');
        if (gettype($filters) === 'array') {
            foreach ($filters as $filter) {
                $field = $filter['field'];
                $value = $filter['value'];
                if ($field == 'team_slug') {
                    $qb->andWhere('UNACCENT(LOWER(t.name)) LIKE UNACCENT(LOWER(:team))')
                        ->setParameter('team', "%{$value}%");
                } elseif ($field == 'id') {
                    $qb->andWhere('UNACCENT(LOWER(d.title)) LIKE UNACCENT(LOWER(:title))')
                        ->setParameter('title', "%{$value}%");
                } elseif ($field == 'category' && $value != ['0' => '']) {
                    $qb->andWhere('d.category = :category')
                        ->setParameter('category', $value);
                } elseif ($field == 'language') {
                    $qb->andWhere('LOWER(d.language) = LOWER(:language)')
                        ->setParameter('language', $value);
                }
            }
        }

        $docs = (clone $qb)
            ->addOrderBy('t.name', 'ASC')
            ->addOrderBy('d.category', 'ASC')
            ->addOrderBy('d.title', 'ASC')
            ->addOrderBy('d.language', 'ASC')
            ->setFirstResult(($pageNum - 1) * $pageSize)
            ->setMaxResults($pageSize)
            ->getQuery()
            ->getResult();
        $count = $qb->select('count(d.id)')
            ->getQuery()
            ->getSingleScalarResult();

        $encoders = [new JsonEncoder()];
        $normalizers = [new ObjectNormalizer()];
        $serializer = new Serializer($normalizers, $encoders);
        $normalDocs = $serializer->normalize($docs, null, [
            AbstractNormalizer::ATTRIBUTES => [
                'id',
                'fileId',
                'filename',
                'title',
                'category',
                'language',
                'team' => [
                    'name',
                    'slug',
                ],
            ],
        ]);
        foreach ($normalDocs as &$row) {
            $row['team_name'] = $row['team']['name'];
            $row['team_slug'] = $row['team']['slug'];
            unset($row['team']);
        }
        $jsonContent = $serializer->serialize(
            [
                'last_page' => ceil($count / $pageSize),
                'data' => $normalDocs,
            ],
            'json'
        );

        return JsonResponse::fromJsonString($jsonContent);
    }

    #[Route(path: '/documents/{id}.{_format}', name: 'document_show', format: 'html', requirements: ['id' => '[\d-]+', '_format' => 'html|json'])]
    public function showDocument(Request $request, int $id, Filesystem $documentsFilesystem): Response
    {
        $document = $this->doctrine
            ->getRepository(Document::class)
            ->find($id);

        if (!$document) {
            throw $this->createNotFoundException('No document found for id '.$id);
        }

        $fileSize = $documentsFilesystem->fileSize($document->getFilePath());

        $format = $request->getRequestFormat();
        if ($format == 'html') {
            return $this->render('document/documentShow.html.twig', [
                'document' => $document,
                'fileSize' => $fileSize,
            ]);
        } elseif ($format == 'json') {
            $encoders = [new JsonEncoder()];
            $normalizers = [new ObjectNormalizer()];
            $serializer = new Serializer($normalizers, $encoders);
            $normalDocument = $serializer->normalize($document, null, [
                AbstractNormalizer::ATTRIBUTES => [
                    'id',
                    'fileId',
                    'filename',
                    'title',
                    'category',
                    'language',
                    'team' => [
                        'name',
                        'slug',
                    ],
                ],
            ]);
            $normalDocument['fileSize'] = $fileSize;
            $jsonContent = $serializer->serialize(
                ['document' => $normalDocument],
                'json'
            );

            return JsonResponse::fromJsonString($jsonContent);
        } else {
            throw new NotAcceptableHttpException('Unknown format: '.$format);
        }
    }

    #[Route(path: '/documents/{id}/download', name: 'document_download', requirements: ['id' => '[\d-]+'])]
    public function downloadDocument(Request $request, int $id, Filesystem $documentsFilesystem): Response
    {
        $document = $this->doctrine
            ->getRepository(Document::class)
            ->find($id);

        if (!$document) {
            throw $this->createNotFoundException('No document found for id '.$id);
        }

        $downloadableFileStream = $documentsFilesystem->readStream($document->getFilePath());
        $mimeType = $documentsFilesystem->mimeType($document->getFilePath());
        $fileSize = $documentsFilesystem->fileSize($document->getFilePath());
        $filename = $document->getFilename();

        if (ob_get_level()) {
            ob_end_clean();
        }

        return new StreamedResponse(function () use ($downloadableFileStream) { // use ($downloadableFileStream, $mimeType, $filename) {
            fpassthru($downloadableFileStream);
        }, 200, [
            'Content-Transfer-Encoding', 'binary',
            'Content-Type' => 'application/octet-stream',
            'Content-Disposition' => ('attachment; filename="'.$filename.'"'),
            'Content-Length' => $fileSize,
        ]);
    }

    #[Route(path: '/documents/{id}/pages.json', name: 'document_download_pages_metadata', requirements: ['id' => '[\d-]+'])]
    public function downloadPagesMetadata(Request $request, int $id, Filesystem $documentsFilesystem): Response
    {
        $document = $this->doctrine
            ->getRepository(Document::class)
            ->find($id);

        if (!$document) {
            throw $this->createNotFoundException('No document found for id '.$id);
        }
        $jsonPath = $document->getFilePath().'_pages.json';

        $downloadableFileStream = $documentsFilesystem->readStream($jsonPath);
        $mimeType = $documentsFilesystem->mimeType($jsonPath);
        $fileSize = $documentsFilesystem->fileSize($jsonPath);
        $filename = $document->getFilename().'_pages.json';

        if (ob_get_level()) {
            ob_end_clean();
        }

        return new StreamedResponse(function () use ($downloadableFileStream) { // use ($downloadableFileStream, $mimeType, $filename) {
            fpassthru($downloadableFileStream);
        }, 200, [
            'Content-Transfer-Encoding', 'binary',
            'Content-Type' => 'application/json',
            'Content-Disposition' => ('attachment; filename="'.$filename.'"'),
            'Content-Length' => $fileSize,
        ]);
    }

    #[Route(path: '/teams/{slug}/new-document', name: 'document_create')]
    #[IsGranted('ROLE_ADMIN')]
    public function createDocument(Request $request, string $slug, DocumentPersister $persister): Response
    {
        /** @var TeamRepository */
        $teamRepo = $this->doctrine->getRepository(Team::class);
        $team = $teamRepo->findBySlug($slug);

        if (!$team) {
            throw $this->createNotFoundException('No team found for slug '.$slug);
        }

        $document = new Document();
        $document->setTeam($team);
        $form = $this->createForm(DocumentType::class, $document, [
            'is_new' => true,
        ]);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {

templates/document/documentDelete.html.twig
{% extends "base.html.twig" %}

{% block title %}Delete document{% endblock %}

{% block body %}
  <h1>Delete document</h1>
  <a href="{{ document.fileUrl }}">{{ document.title }}</a>
  <p>Are you sure you want to delete this document?</p>
  {{ form(form, {'attr': {'data-controller': 'delete'}}) }}
{% endblock %}

templates/document/documentEdit.html.twig
{% extends "base.html.twig" %}

{% block title %}{{ team.name }} – edit document{% endblock %}

{% block body %}
  <h1>
    <a href="/teams/{{ team.slug }}">{{ team.name }}</a>
    – edit document
  </h1>
  {{ form(form) }}
{% endblock %}

templates/document/documentList.html.twig
{% extends "base.html.twig" %}

{% block title %}{{ 'documentList.title'|trans }}{% endblock %}

{% block stylesheets %}
{{ parent() }}
<style>
#documentsTable {
  max-height: 80vh;
}
</style>
{% endblock %}

{% block body %}
  <h1>{{ 'documentList.title'|trans }}</h1>
  <noscript>
    <div class="alert alert-warning" role="alert">
      {{ 'general.noscript'|trans }}
    </div>
  </noscript>
  <div id="documentsTable" {{ stimulus_controller('document-list', { 'categories': documentInfo.categories }) }}></div>
{% endblock %}

templates/document/documentNew.html.twig
{% extends "base.html.twig" %}

{% block title %}{{ team.name }} – add document{% endblock %}

{% block body %}
  <h1>
    <a href="/teams/{{ team.slug }}">{{ team.name }}</a>
    – add document
  </h1>
  {{ form(form) }}
{% endblock %}

templates/document/documentShow.html.twig
{% extends "base.html.twig" %}

{% block title %}{{ 'documentShow.title'|trans({'%title%': document|describe_document, '%team%': document.team.name}) }}{% endblock %}

{% block meta %}
{# TODO: ideally thumbnail should be a separate, reliable URL (in case page numbering ever changes) and should perhaps be lower resolution? #}
{% if document.isBookReader %}
  <meta property="og:image" content="{{ document.fileUrl }}_page000001.png" />
{% elseif document.fileExtension in ['png', 'jpg', 'jpeg', 'gif', 'webp'] %}
  <meta property="og:image" content="{{ document.fileUrl }}" />
{% endif %}
{% endblock meta %}

{% block stylesheets %}
{{ parent() }}
<link rel="stylesheet" href="/build/BookReader/BookReader.css">
<style>
.embed-image {
  max-height: 600px;
  display: block;
}
.pdf-wrapper {
  position: relative;
  padding-bottom: 60%;
}
.pdf-wrapper iframe {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
}
.document-metadata th {
  width: 6em;
}

/***** BookReader *****/

/* Hide print and embed functionality */
.BRtoolbar .embed, .print {
  display: none;
}

body.BRfullscreenActive section.theater {
  height: 100vh;
}
ia-bookreader[fullscreen] {
  height: unset;
}

ia-bookreader{
  display: block;
  height: calc(100vh - 250px);
}

.BookReader {
  height: calc(100vh - 250px);
  overflow: hidden;
  margin: 0 auto;
}

@media only screen and (max-width: 799px) {
  body.BRbodyMobileNavEnabled {
    margin: 0;
    width: 100%;
    overflow: hidden;
  }
  .BRbodyMobileNavEnabled .BookReader {
    top: 0;
    bottom: 0;
    left: 0;
    right: 0;
    position: absolute;
    height: 100%;
    margin: 0;
    width: 100%;
  }
}

/* don't need info/share */
.BRtoolbarSectionInfo {
  display: none;
}
</style>
{% endblock %}

{% block javascripts %}
<script src="/build/BookReader/webcomponents-bundle.js"></script>
<script src="/build/BookReader/jquery-3.js"></script>
<script src="/build/BookReader/BookReader.js"></script>
<script src="/build/BookReader/plugins/plugin.url.js"></script>
{{ parent() }}
{{ encore_entry_script_tags('documentShow') }}
{% endblock %}


{% block body %}
  <div id="jsData" class="d-none"
    data-file-url="{{ document.fileUrl }}"
    data-document-id="{{ document.id }}"
    ></div>
  <div class="h5 mb-0">
    <a href="/teams/{{ document.team.slug }}">{{ document.team.name }}</a>
    {{ document.category|replace({'-': ' '}) }}
  </div>
  <h1>
    {{ document|describe_document }}
  </h1>
  {% if is_granted('ROLE_ADMIN') %}
    <a href="/documents/{{ document.id }}/edit" class="btn btn-sm btn-primary mb-3">
      <i class="i-pen"></i>
      {{ 'general.edit'|trans }}
    </a>
    <a href="/documents/{{ document.id }}/delete" class="btn btn-sm btn-danger mb-3">
      <i class="i-trash"></i>
      {{ 'general.delete'|trans }}
    </a>
  {% endif %}
  <div class="mb-3 border border-5 rounded bg-dark text-white">
    {% if document.fileExtension in ['pdf'] %}
      {% if document.isBookReader %} {# try to use BookReader if assets have been pre-generated #}
        <div id="BookReader">
          <div class="h1 my-5 text-center"><i class="i-spinner icon-spin"></i> Loading book reader...</div>
          <noscript>
          <p>
            {{ 'general.noscript'|trans }}
          </p>
          </noscript>
        </div>
      {% else %} {# fallback to pdf.js if BookReader assets don't exist #}
        <div class="pdf-wrapper">
          <iframe src="/pdfjs/web/viewer.html?file=/documents/{{ document.id }}/download"></iframe>
        </div>
      {% endif %}
    {% elseif document.fileExtension in ['png', 'jpg', 'jpeg', 'gif', 'webp', 'tif', 'bmp', 'svg'] %}
      <img src="{{ document.fileUrl }}" class="embed-image img-fluid mx-auto" />
    {% else %}
      <div class="p-5 text-white display-5 text-center">
        {{ 'documentShow.noPreview'|trans }}
      </div>
    {% endif %}
  </div>
  <div class="float-md-end">
    <a href="{{ document.fileUrl }}" class="btn btn-success btn-lg mb-3">
      <i class="i-download"></i>
      {{ 'documentShow.download'|trans }}
    </a>
  </div>
  <div class="col-md-6 document-metadata">
    <table class="table table-bordered">
      <tr>
        <th>{{ 'documentShow.fileType'|trans }}</th>
        <td>
          <i class="{{ _self.getFileIcon(document.fileExtension) }}"></i>
          {{ document.fileExtension|upper }}
        </td>
      </tr>
      <tr>
        <th>{{ 'documentShow.fileSize'|trans }}</th>
        <td>{{ _self.bytesToSize(fileSize) }}</td>
      </tr>
      <tr>
        <th>{{ 'documentShow.language'|trans }}</th>
        <td>{{ document.language|language_name|default("general.noLanguage"|trans) }}</td>
      </tr>
      <tr>
        <th>{{ 'documentShow.notes'|trans }}</th>
        <td>{{ document.notes }}</td>
      </tr>
    </table>
  </div>
{% endblock %}

{% macro getFileIcon(ext) %}
{% apply spaceless %}
  {% set fileIcons  = {
    'pdf': 'i-file-pdf',
    'zip': 'i-file-archive',
    'rar': 'i-file-archive',
    'gz': 'i-file-archive',
    'doc': 'i-file-word',
    'docx': 'i-file-word',
    'odt': 'i-file-word',
    'fodt': 'i-file-word',
    'ppt': 'i-file-powerpoint',
    'pptx': 'i-file-powerpoint',
    'odp': 'i-file-powerpoint',
    'fodp': 'i-file-powerpoint',
    'xls': 'i-file-excel',
    'xlsx': 'i-file-excel',
    'ods': 'i-file-excel',
    'fods': 'i-file-excel',
    'csv': 'i-file-csv',
    'json': 'i-file-code',
    'html': 'i-file-code',
    'htm': 'i-file-code',
    'txt': 'i-file-alt',
    'rtf': 'i-file-alt',
    'jpg': 'i-file-image',
    'jpeg': 'i-file-image',
    'png': 'i-file-image',
    'gif': 'i-file-image',
    'webp': 'i-file-image',
    'bmp': 'i-file-image',
    'tif': 'i-file-image',
    'svg': 'i-file-image',
    'eps': 'i-file-image',
    'psd': 'i-file-image',
    'xcf': 'i-file-image',
    'cr2': 'i-file-image',
    'odg': 'i-file-image',
    'fodg': 'i-file-image',
    'm4a': 'i-file-audio',
    'mp3': 'i-file-audio',
    'mka': 'i-file-audio',
    'wma': 'i-file-audio',
    'wav': 'i-file-audio',
    'opus': 'i-file-audio',
    'ogg': 'i-file-audio',
    'oga': 'i-file-audio',
    'mov': 'i-file-video',
    'mpg': 'i-file-video',
    'mpeg': 'i-file-video',
    'mp4': 'i-file-video',
    'avi': 'i-file-video',
    'webm': 'i-file-video',
    'mkv': 'i-file-video',
    'wmv': 'i-file-video',
    'ogv': 'i-file-video',
  }
  %}
  {{ ext in fileIcons|keys ? fileIcons[ext] : "i-file" }}
{% endapply %}
{% endmacro %}

{# https://stackoverflow.com/a/15303004/992504 #}
{% macro bytesToSize(bytes) %}
{% apply spaceless %}
    {% set kilobyte = 1024 %}
    {% set megabyte = kilobyte * 1024 %}
    {% set gigabyte = megabyte * 1024 %}
    {% set terabyte = gigabyte * 1024 %}

    {% if bytes < kilobyte %}
        {{ bytes ~ ' B' }}
    {% elseif bytes < megabyte %}
        {{ (bytes / kilobyte)|number_format(2, '.') ~ ' KiB' }}
    {% elseif bytes < gigabyte %}
        {{ (bytes / megabyte)|number_format(2, '.') ~ ' MiB' }}
    {% elseif bytes < terabyte %}
        {{ (bytes / gigabyte)|number_format(2, '.') ~ ' GiB' }}
    {% else %}
        {{ (bytes / terabyte)|number_format(2, '.') ~ ' TiB' }}
    {% endif %}
{% endapply %}
{% endmacro %}